spring:
    profiles: dev #开发环境
    application:
        #服务名称
        name: spring-cloud-demo-goods-dev

spring:
    profiles: test #开发环境
    application:
        #服务名称
        name: spring-cloud-demo-goods-test